### ISSUE TITLE
Add support for iPhone SE

### ISSUE THREAD

**Issue by 1252768804** [corellium/projectsandcastle#11]
iPhone SE is the same CPU as the 6S

**Comment by xcybermanx** [comment]
yes add it i have iphone SE but i

**Comment by IMS212** [comment]
It’s not that easy. If you even took a moment to look at the code of the kernel, you would see many things require changes or rebuilds. Adding support for something isn’t as easy as flipping a switch, even with the same cpu, the display, battery, and Wifi chip(?) are all different, so drivers have to be made for those.

**Comment by wisecrick** [comment]
I also strongly suggest add iPhone SE support, because it's widely used in many countries.

**Comment by MajickTek** [comment]
@wisecrick read what @IMS212 said. It’s not like flipping a switch. Actual work has to be done and it’s hard. This project doesn’t even support the 6S yet as far as I’m aware.

**Comment by cmwdotme** [comment]
Added it to the status page. No promises if/when it will be done.
