### ISSUE TITLE
Failed to copy setup script

### ISSUE THREAD

**Issue by pir7** [corellium/projectsandcastle#12]
I always received the same error ;
iPhone 7+ running iOS 13.3.1 with 0.9.8.1 .
./setup_mac.sh
Starting setup
Failed to copy setup script

**Comment by kingknuts** [comment]
Make sure you can ssh your device. The script uses the default password alpine. If you changed it, you need to change also in the script

**Comment by pir7** [comment]
yeah I can ssh just fine with
ssh root@"ip"
with password alpine, note that I can use it fine with my iPod 7gen but I wanna try it on my i7+ with no success.

**Comment by rootedetc** [comment]
Change your ssh password back to alpine, or if you want to use a custom one - change it in the script as @kingknuts suggested.

If you are still facing issues, go to Finder > Go > Go to Folder > ~/.ssh and delete known hosts file.

**Comment by pir7** [comment]
ooh thanks removing known hosts solved the issue

**Comment by rootedetc** [comment]
Glad it worked for you, @pir7 
If you don't have further questions, please close the issue :)
