### ISSUE TITLE
Couldn't find device when running ./load-linux 

### ISSUE THREAD

**Issue by marleyqp** [corellium/projectsandcastle#14]
Even though my device is plugged in (I tried Normal, Recovery and DFU mode) and it wont find it

**Comment by kenan1099** [comment]
This is a problem with the readme file where it doesn't specify that you have to run pongoOS. (it's present in linux readme but not android readme)
Anyways just enter DFU, run (sudo) `checkra1n -cp` then run `./load-linux`

**Comment by marleyqp** [comment]
fixed. thank you
