### ISSUE TITLE
Switch between jail broken iOS and android without reboot

### ISSUE THREAD

**Issue by Watking01** [corellium/projectsandcastle#15]
I don’t think this is possible but is there a way to boot into android and back without properly rebooted, maybe ldrestarting into android or something, because android isn’t exactly fully functional, but it’s still useful to have without having to reboot. Great work by the way, this is amazing and works much better than any vm, and even some android phones. Thank you to the whole community that helped.

**Comment by marleyqp** [comment]
Did you do this on Linux/Mac?
And no, it's impossible. Although in the future maybe they'll add as an option.

**Comment by IMS212** [comment]
Booting into android is probably impossible from iOS, but the other way around may work due to having (direct?) access to iBoot

**Comment by cmwdotme** [comment]
Likely won't happen. Sorry :)
