### ISSUE TITLE
_clock__gettime error on el capitan

### ISSUE THREAD

**Issue by Ofdas-23** [corellium/projectsandcastle#17]
Hello there,

I am having troubles following the instructions. I use el capitan and read that it doesnt implemented _clock__gettime yet, my problem is, that I cant update my mac past el capitan.

I have a laptop runnin sierra, but my problem on this is, it´s one of the types, which for example wont with checkrain (checkrain gives error 10), thus I cant put my device in DFU mode when terminal is waiting for device in DFU. The thing is, PongoOS booted(?) (initializing AIC 2) and it is stuck at "pongoOS> set xnu boot arg cmdline to: [rootdev:md0]" and sierra´s terminal is stuck at "please put your device into DFU"

Here is el capitan´s terminal´s output:
~ ******$ /Users/******/Downloads/android-sandcastle/start_mac.sh 
Please put your device into DFU
Found DFU device. Starting
Pongo loaded. Give it a second
Starting Android
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/******/Downloads/android-sandcastle/./load-linux.mac
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/******/Downloads/android-sandcastle/./load-linux.mac
  Expected in: /usr/lib/libSystem.B.dylib

/Users/******/Downloads/android-sandcastle/start_mac.sh: line 42:  7843 Trace/BPT trap: 5       ./load-linux.mac Android.lzma dtbpack

is there any work-around?

thanks in advance!

**Comment by cmwdotme** [comment]
This is because it's built for a newer version of Mac OS than you have. You can check out the loader from https://github.com/corellium/projectsandcastle.git and build it. That will fix it.

**Comment by Ofdas-23** [comment]
@cmwdotme Now I get the following right after it says "starting android": /Users/******/Downloads/android-sandcastle/start_mac.sh: line 42: 21348 Killed: 9               ./load-linux.mac Android.lzma dtbpack

I think I am stupid for this...
Anyway thhank you.
