### ISSUE TITLE
Support for iPhone 5c

### ISSUE THREAD

**Issue by skyfaller** [corellium/projectsandcastle#18]
Hi folks, I see from [the status chart](https://projectsandcastle.org/status) that the iPhone 5c is not supported at all. Is there any chance that this could change, or is there some fundamental architectural / physical reason why the 5c is not supported? I have access to an iPhone 5c that I could use for testing.

**Comment by ReubenBTalbott** [comment]
The iPhone 5c is 32bit while the iPhone 5s and newer are 64bit, I would guess this is why.

**Comment by cmwdotme** [comment]
It *maybe* added in the future. Currently it does support both 32bit & 64bit execution.

**Comment by Heath123** [comment]
Also as far as I know it doesn't have checkra1n
