### ISSUE TITLE
Questions building Android

### ISSUE THREAD

**Issue by xingrz** [corellium/projectsandcastle#25]
1. How is the `Android.lzma` (in `android-sandcastle.zip`) being built? Is it the kernel image?
2. How is the `nand` (unzipped from `nand.gz`) being constructed? Is it a 256-blocks header + vbmeta + super + sdcard?

**Comment by cmwdotme** [comment]
To build we use :
export LC_ALL=C
export OUT_DIR=out-sandcastle
source build/make/envsetup.sh
lunch sandcastle_arm64-userdebug
make -j36

**Comment by xingrz** [comment]
> source build/make/envsetup.sh
> lunch sandcastle_arm64-userdebug
> make -j36

I know but you didn't mentioned how to build the kernel (Android.lzma)
