### ISSUE TITLE
Touch not working when using a aftermarket display. (iPhone 7)

### ISSUE THREAD

**Issue by AntonioAbilio** [corellium/projectsandcastle#28]
Although android boots fine on my iPhone 7 I found out that the non original display that I’m currently using, makes the touchscreen unusable. Since I change my own displays, I still had the old one and when plugging it in and booting up android I can confirm that everything works fine even the touchscreen and multitouch.

**Comment by AntonioAbilio** [comment]
I’m using the android on my iPhone still. Live it, keep up the good work.

**Comment by TheNameIsNigel** [comment]
This is a duplicate of issue #10 .

**Comment by Stan-Corellium** [comment]
Closing as duplicate of #10.
