### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by nathanielcwm** [corellium/projectsandcastle#3]
It appears like iPads aren't on the compatibility list.
Would iPads be supported in the future?

**Comment by frankcom** [comment]
Very interesting point, interested in answer too!

**Comment by IMS212** [comment]
Most likely they will, once iPhone support is complete iPads should have most of the drivers already made due to having very similar hardware.

**Comment by cmwdotme** [comment]
iPads maybe supported in the future. They weren't added to the list because we were in a rush. We will update at some point to include them :)

**Comment by frankcom** [comment]
Thanks for doing this great project!
Is there also the other way round? ios for Android?? ;)
