### ISSUE TITLE
Error of making /loader/load-Linux.c 

### ISSUE THREAD

**Issue by TeslaHacks** [corellium/projectsandcastle#31]
There are errors about libusb. 
How to fix it?
(I’m using Lubuntu 64-bit)
Thanks:)
![62079FD0-94DA-4DB5-B3AF-CDD22BE18442](https://user-images.githubusercontent.com/51783455/76156916-cb051600-6144-11ea-9315-7d87843897de.jpeg)

**Comment by AntonioAbilio** [comment]
1°) Install gcc, make, and libusb-1.0-0-dev. 
2°) Cd into the folder that you want to compile and use “gcc load-linux.c -o load-linux -lusb-1.0” and after that use “chmod +x load-linux”.
