### ISSUE TITLE
Uncertain with instructions for Linux build

### ISSUE THREAD

**Issue by IceCryptonym** [corellium/projectsandcastle#33]
I am not entirely sure what to do with these instructions.
`The linux build comes with a baked in ramdisk. It will automatically bring up X windows after boot. It will create a gadget usb interface on the host computer and if you set the IP address of the interface to 172.16.1.2/255.255.255.0 you will be able to access the iPhone at 172.16.1.1. Once its booted you can login via ssh with root/alpine.`
What interface is it talking about and how do I access it?

**Comment by cmwdotme** [comment]
Android will expose a gadget usb interface to whatever your host OS is. In Mac OS this will show up in network preferences as "CDC Connection Gadget". Assign the IP 172.16.1.2 with the net mask 255.255.255.0 and you will be able to ssh to 172.16.1.1 (the Android device)
