### ISSUE TITLE
Bricked with custom system image

### ISSUE THREAD

**Issue by xingrz** [corellium/projectsandcastle#35]
I just compiled my customized super.img, ran `filldisk.sh` to construct  a `nand` file, and scp copied it to `/tmp/mnt`.

I ran `start_mac.sh`, saw pongoOS and sandcastle linux. Then, after a few lines of errors (something like "image not found", I can't remember clearly), it reboots into iOS. And then, seconds later, it turned black.

I've tried holding volume down and power button for seconds, nothing happened. It didn't up again.

I know something must be wrong with my system image. I just wondering if there's a way to bring it back to life. lol

**Comment by cmwdotme** [comment]
It's likely your battery is dead. It's really not possible to brick a device using the tools we provided. Try plugging it in and letting it charge for a few minutes and holding the hold button for 10 seconds. If that doesn't work try holding volume down and the hold button for 10 seconds.

**Comment by xingrz** [comment]
One more difference I've just noticed: I didn't realized the image I've built is an _Android sparse image_, while the actual `super.img` extracted from `nand.gz` is a raw image.

**Comment by cmwdotme** [comment]
Did you mount the disk before transferring to /tmp/mnt? You can use mkdisk.sh to make the nand image and gzip nand to make the .gz

**Comment by xingrz** [comment]
Yes, I mounted it.

Never mind, I'll send it to the studio for repairing. Just wanna note down what's happened on my phone here.
