### ISSUE TITLE
SUGGESTION: Project SandCastle to Project OpenGarden

### ISSUE THREAD

**Issue by TheEvilSkeleton** [corellium/projectsandcastle#4]
Given iOS being a walled garden, it would be awesome if the project's name is OpenGarden.

**Comment by ChefTyler** [comment]
I think that is a great idea, or libreGarden if OpenGarden isn't liked, just something to show that we have broken the walled off garden that is iOS.

**Comment by cmwdotme** [comment]
Sorry we already bought the t-shirts.
