### ISSUE TITLE
Failed to copy setup script

### ISSUE THREAD

**Issue by raf1dd** [corellium/projectsandcastle#8]
![image](https://user-images.githubusercontent.com/22422727/75946372-e8975e80-5e6a-11ea-95a2-db38a3d42478.png)

i am on osx 10.15.2 

tried disabling gateway and sip still same error :/

**Comment by VergeDX** [comment]
try `sudo` ?

**Comment by raf1dd** [comment]
> try `sudo` ?

that seems to have done something it's saying "starting to download nand. This will take a few minutes" is this good?

**Comment by raf1dd** [comment]
"starting to download nand. This will take a few minutes" its actually stuck here for the past 3 minutes

**Comment by raf1dd** [comment]
thanks a lot that seems to have done it <3
